### PR TITLE
[BUGFIX] Event type incorrect when loading projection streams

### LINKED ISSUE #13: EventType wrong when reading projections
This is due to the fact that the summary field contains anything but the EventType ("$>") when reading streams that are based on projections. The events (and the data) itself are fetched normally.

A possible solution to this problem is to set the feeds embed mode to FULL and fix the `EventStore\StreamFeed\Entry::getType()` like this:

```
return (isset($this->json['eventType'])) ? $this->json['eventType'] : $this->json['summary'];
```

Should this be an acceptable solution, I'd gladly provide a pull-request.

### PR DESCRIPTION
**Pull request by Akii**
This is due to the fact, that the summary field in the response
is no longer the event type.

This test uses a fixture which is returned from an event store
v3.0.3.

Resolves #13

### CODE REVIEW

File: tests/EventStore/Tests/StreamFeed/EntryTest.php [hunk 1]
```diff
@@ -11,4 +11,16 @@ public function testTypeGetter()
...
         $this->assertEquals('Bar', $entry->getType());
     }
-}
+
+    /**
+     * @test
+     */
+    public function theEventTypeForEntriesOfAnProjectionStreamFeedIsCorrect(){
+        $json = file_get_contents(__DIR__ . '/Fixtures/RichEventStoreCeEntryResponse.json');
+        $entryData = json_decode($json, TRUE);
```
Comment (dbellettini) [inline tests/EventStore/Tests/StreamFeed/EntryTest.php]: please run php-cs-fixer to fix coding standard (if you're using Linux just copy hooks/pre-commit in .git/hooks)

**Comment by Akii** [comment]
Fixed. Magic! If this Scrutiblah thing would print out better errors I would've fixed it earlier :)
